### ISSUE TITLE
[drivers] UART

### ISSUE THREAD

**Issue by arunthomas** [lowRISC/tock#13]
# Description
Implement Tock driver for gpio
# Tasks
- [x] Audit the driver for missing functionality
- [x] Implement any missing driver functionality
- [x]  Implement missing HIL functionality (if needed)
- [ ]  Implement tests

**Comment by jon-flatley** [comment]
Task List:

- [x] `RecieveAdvanced` implementation
- [ ]  ~~Create a HIL for `alert_test`.~~
- [x]  Ensure `Transmit::transmit_abort`, `Transmit::transmit_word`, `Receive::receive_abort`, and `Receive::receive_word` always fail as they do for all other Tock boards. Investigate if an implementation for these functions is needed.
- [ ]  Implement interrupts:
  - [ ]  `TX_WATERMARK` - Logic or notification relating to the watermark.
  - [x]  `RX_OVERFLOW`
  - [x]  `RX_FRAME_ERR`
  - [x]  `RX_BREAK_ERR` - UART has disconnected, send error to client. Support error in HIL?
  - [x]  `RX_TIMEOUT` - Send error to client. Support error in HIL?
  - [x]  `RX_PARITY_ERR`
- [ ]  ~~Interrupt test~~
- [ ]  Config parameters and validation. Fields that need to be added to `UartParams`:
  - [x]  Baud rate
  - [x]  Parity
  - [ ]  Stop bit
  - [ ]  Width check

**Comment by rnongie** [comment]
Note - This task has been simplified to focus on implementing driver functionality.
The "implement driver tests" has been moved to #39 

Please feel free to close this task when driver functionality is complete.
