### ISSUE TITLE
[drivers] i2c

### ISSUE THREAD

**Issue by arunthomas** [lowRISC/tock#14]
# Description
Implement Tock driver for i2c
# Tasks
- [ ] Audit the driver for missing functionality
- [ ] Implement any missing driver functionality
- [ ]  Implement missing HIL functionality (if needed)
- [ ]  Implement tests

**Comment by rnongie** [comment]
Note - This task has been simplified to focus on implementing driver functionality.
The "implement driver tests" has been moved to #32 

Please feel free to close this task when driver functionality is complete.
