### ISSUE TITLE
[drivers] alert_handler

### ISSUE THREAD

**Issue by arunthomas** [lowRISC/tock#23]
# Description
Implement Tock driver for alert_handler
# Tasks
- [ ] Audit the driver for missing functionality
- [ ] Implement any missing driver functionality
- [ ] Implement missing HIL functionality (if needed)
- [ ] Implement tests

**Comment by rnongie** [comment]
Note - This task has been simplified to focus on implementing driver functionality.
The "implement driver tests" has been moved to #43 

Please feel free to close this task when driver functionality is complete.
